{
 "title": "Mailcow",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(mailcow_api_success,job)"
    }
   },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(mailcow_api_success{job=~\"$job\"},host)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(mailcow_domain_aliases{job=~\"$job\", host=~\"$host\"},domain)"
    }
   },
   {
    "name": "mailbox",
    "label": "Mailbox",
    "query": {
     "query": "label_values(mailcow_mailbox_last_login{job=~\"$job\", host=~\"$host\", mailbox=~\".*@$domain\"},mailbox)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=~\"$job\",host=~\"$host\"}) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Domains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mailcow_domain_active{job=~\"$job\",host=~\"$host\"} == 1) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mailcow Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers running",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "mailcow_container_running{job=~\"$job\",host=~\"$host\"}",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "API Endpoint Status",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "mailcow_api_success{job=~\"$job\",host=~\"$host\"}",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Container-Uptime",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "expr": "( time() - mailcow_container_start{job=~\"$job\",host=~\"$host\"}) /3600",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exporter Status",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "mailcow_exporter_success{job=~\"$job\",host=~\"$host\"}",
       "legendFormat": "{{provider}}"
      }
     ]
    }
   ]
  },
  { "title": "RSPAMd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "RSPAMd Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(mailcow_rspamd_action{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "RSPAMd RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mailcow_rspamd_bytes_allocated{job=~\"$job\",host=~\"$host\"}",
     "legendFormat": "Bytes allocated"
    }
   ]
  },
  {
   "title": "RSPAMd Classification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(mailcow_rspamd_classification{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "{{classification}}"
    }
   ]
  },
  {
   "title": "RSPAMd Chunk Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(mailcow_rspamd_chunks{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "RSPAMd Fuzzy Hashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mailcow_rspamd_fuzzy_hashes{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "RSPAMd Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mailcow_rspamd_learned{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "Learned"
    },
    {
     "expr": "rate(mailcow_rspamd_scanned{job=~\"$job\",host=~\"$host\"}[5m])",
     "legendFormat": "Scanned"
    }
   ]
  },
  { "title": "Per Domain Status - $domain -", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "domain" },
  {
   "title": "Domain Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "mailcow_domain_active{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "- $domain - # Addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "mailcow_domain_aliases{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"}",
     "legendFormat": "Aliases"
    },
    {
     "expr": "mailcow_domain_mailboxes{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"}",
     "legendFormat": "Mailboxes"
    }
   ]
  },
  {
   "title": "- $domain - Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(mailcow_domain_messages{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"}[5m])",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Message Statistics per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(mailcow_mailbox_messages{job=~\"$job\",host=~\"$host\",mailbox=~\".*@$domain\"}[5m])",
     "legendFormat": "{{mailbox}}: Messages"
    }
   ]
  },
  {
   "title": "- $domain - Quota used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mailcow_domain_quota_used{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"}) / sum(mailcow_domain_quota_allowed{job=~\"$job\",host=~\"$host\",domain=~\"$domain\"})",
     "legendFormat": "Quota Used"
    }
   ]
  },
  {
   "title": "Last Login",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mailcow_mailbox_last_login{job=~\"$job\",host=~\"$host\",mailbox=~\".*@$domain\"} * 1000",
     "legendFormat": "Last Login"
    }
   ]
  },
  {
   "title": "Quota used per User",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mailcow_mailbox_quota_used{job=~\"$job\",host=~\"$host\",mailbox=~\".*@$domain\"} / mailcow_mailbox_quota_allowed{job=~\"$job\",host=~\"$host\",mailbox=~\".*@$domain\"}",
     "legendFormat": "{{mailbox}}"
    }
   ]
  }
 ]
}